"""create matakuliah table

Revision ID: d1bcff35be38
Revises: 3f6a4614e6e1
Create Date: 2025-05-12 01:09:34.392824

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd1bcff35be38'
down_revision = '3f6a4614e6e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
