def includeme(config):
    config.add_route('get_matakuliah', '/matakuliah', request_method='GET')
    config.add_route('create_matakuliah', '/matakuliah', request_method='POST')
    config.add_route('update_matakuliah', '/matakuliah/{id}', request_method='PUT')
    config.add_route('delete_matakuliah', '/matakuliah/{id}', request_method='DELETE')
    config.add_route('home', '/')
    config.add_route('mahasiswa_add', '/mahasiswa/add')
    config.add_route('mahasiswa_update', '/mahasiswa/update/{id}')
    config.add_route('mahasiswa_delete', '/mahasiswa/delete/{id}')
    config.add_route('mahasiswa_list', '/mahasiswa')
    config.add_route('mahasiswa_detail', '/mahasiswa/{id}')
    config.add_route('mahasiswa_search', '/mahasiswa/search')
    config.add_route('mahasiswa_search_by_nim', '/mahasiswa/search_by_nim')
    config.add_route('mahasiswa_search_by_nama', '/mahasiswa/search_by_nama')
    config.add_route('mahasiswa_search_by_jurusan', '/mahasiswa/search_by_jurusan')
    config.add_route('mahasiswa_search_by_tanggal_lahir', '/mahasiswa/search_by_tanggal_lahir')